<table width="100%">
    <tr>
        <td align="left"><a href="https://www.fgw.vu.nl"><img class="fgwlogo" src="../images/fgw_logo.svg"
                                                              border="0"></a>
            <span class="headertext">Monasteries</span>
            <span class="headerlink">
                <a href="https://gpz.labs.vu.nl/cms/research/kloosterkaart/">Monasteries Map</a>
            </span>
        </td>
    </tr>
</table>
