<html>
<head>
    <LINK rel="stylesheet" href="../resources/mp.css" type="text/css">
    <link rel='stylesheet'
          href='https://fonts.googleapis.com/css?family=Raleway%3A400%2C600&#038;subset=latin&#038;display=swap'
          type='text/css' media='all'/>
</head>
<body>
<hr class="hrmenu">
<a href="index.php" class="menu">&raquo; Introduction</a><br/>
<a href="kform.php" class="menu">&raquo; Monasteries</a><br/>
<a href="urform.php" class="menu">&raquo; Granges &</em></a><br/>
<a href="urform.php" class="menu">Refuges</em></a><br/>
<a href="tform.php" class="menu">&raquo; Houses of</em></a><br/>
<a href="tform.php" class="menu">terminarii</em></a><br/>
<a href="kapform.php" class="menu">&raquo; Collegiate</em></a><br/>
<a href="kapform.php" class="menu">churches</em></a><br/>
<a href="elim.php" class="menu">&raquo; List of</a><br/>
<a href="elim.php" class="menu">Eliminations</a><br/>
<a href="czoek.php" class="menu">&raquo; Concordance</a><br/>
<a href="topverw.php" class="menu">&raquo; Topographical</a><br/>
<a href="topverw.php" class="menu">Index</a><br/>
<a href="lit.php" class="menu">&raquo; Bibliographies</a><br/>
<a href="col.php" class="menu">&raquo; Colophon</a><br/>
<br/><br/>
<hr class="hrmenu">

<a href="<?= str_replace("en", "nl", $_SERVER['REQUEST_URI']) ?>" class="menu">&raquo; Dutch</a>
<a href="<?= str_replace("en", "nl", $_SERVER['REQUEST_URI']) ?>" class="menu"><img src="../images/dutch.png"
                                                                                    border="0"></a>
<hr class="hrmenu">

</body>
</html>

