<table width="100%">
    <tr>
        <td align="left"><a href="http://www.fgw.vu.nl"><img class="fgwlogo" src="images/fgw_logo.svg" border="0"></a><a class="headerlink" href="http://geoplaza.vu.nl">Geoplaza Home</a></td>
        <td align="right"><a href="http://www.vu.nl"><img src="images/grif.gif" width="312" height="104" border="0"></a>
        </td>
    </tr>
</table>
<h1 class="indent">Kloosterlijst</h1>