<html>
<head>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Raleway%3A400%2C600&#038;subset=latin&#038;display=swap' type='text/css' media='all' />
</head>
<body>
<hr class="hrmenu">
<a href="index.php" class="menu">&raquo; Inleiding</a><br/>
<a href="kform.php" class="menu">&raquo; Kloosters</a><br/>
<a href="urform.php" class="menu">&raquo; Uithoven &</a><br/>
<a href="urform.php" class="menubr">Refugia</a><br/>
<a href="tform.php" class="menu">&raquo; Termijnhuizen</a><br/>
<a href="kapform.php" class="menu">&raquo; Kapittels</a><br/>
<a href="elim.php" class="menu">&raquo; Eliminatielijst</a><br/>
<a href="czoek.php" class="menu">&raquo; Concordantie</a><br/>
<a href="topverw.php" class="menu">&raquo; Topografische</a><br/>
<a href="topverw.php" class="menubr">index</a><br/>
<a href="lit.php" class="menu">&raquo; Bibliografie&euml;n</a><br/>
<a href="voorenna.php" class="menu">&raquo; Voor en na 1800</a><br/>
<a href="col.php" class="menu">&raquo; Colofon</a><br/>
<br/><br/>
<hr class="hrmenu">
<a href="<?= str_replace("nl", "en", $_SERVER['REQUEST_URI']) ?>" class="menu">&raquo; Engels</a>
<a href="<?= str_replace("nl", "en", $_SERVER['REQUEST_URI']) ?>"><img src="../images/english.png" border="0"></a>
<hr class="hrmenu">
</body>
</html>

